let shopItemsData = [
  {
    id: "a980990",
    name: "Casual Shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/img-1.jpg",
  },
  {
    id: "b8394049",
    name: "Office Shirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/img-2.jpg",
  },
  {
    id: "c1823094",
    name: "T Shirt",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/img-3.jpg",
  },
  {
    id: "d1039457",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/img-4.jpg",
  },
  {
    id: "e9023178",
    name: "Tie",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/img-5.png",
  },
  {
    id: "f0192637",
    name: "Sneakers",
    price: 560,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/img-6.png",
  },
  {
    id: "g0917289",
    name: "Mens Jacket",
    price: 800,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/img-7.png",
  },
  {
    id: "h1920377",
    name: "Mens T-shirt",
    price: 234,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/img-8.png",
  },
  {
    id: "i9028376",
    name: "Mens T-shirt",
    price: 456,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/img-9.png",
  },
  {
    id: "j1892349",
    name: "Mens Jeans",
    price: 763,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/img-10.png",
  },
  {
    id: "k0192837",
    name: "Cap",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/img-11.png",
  },
  {
    id: "l0192837",
    name: "Mens Boots",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "../images/img-12.png",
  },
];
